trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_location: './src' # App source code path relative to cwd
      api_location: '' # Api source code path relative to cwd
      output_location: './src' # Built app content directory relative to app_location - optional
      cwd: '$(System.DefaultWorkingDirectory)' # Working directory - optional
      azure_static_web_apps_api_token: $(deployment_token)
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here        
        echo 'Hello world!'